### ISSUE TITLE
libsmfilter.so: No such file or directory

### ISSUE THREAD

**Issue by kuttkutt** [rahra/smrender#4]
hmm, I think the latest release is too old, to get it running on Debian 9.4

Since the documentation seems very outdated it was a pain to find all the packages to get smrender even to compile

however, no matter what I try, I always get:
could not open library: libsmfilter.so: cannot open shared object file: No such file or directory

However, the lib is there: /usr/local/lib/libsmrender.so (symlinked to libsmrender.so.0.1.0)

The next issue: The examples in the documentation are outdated. Broken links and wrong information. 

I guess this project was given up long long time ago - Does anyone know a similar tool to create your own seacharts?

**Comment by rahra** [comment]
What version are you using? At which documentation are you looking at?
The tool actual is up to date I just had not much time the last few months.

If you give me some more precise hints about which links are broken and which parts of the documentation is incorrect I'll fix it and give you advice on how to do it. Please note that there is a very complete ruleset included and some simple test cases/rules are found in the test folder.

The error message _'could not open library: libsmfilter.so: cannot open shared object file: No such file or directory'_ comes from your dynamic linker of your system which didn't update the library cache after installation. Simply reboot the system and this will go away.

**Comment by kuttkutt** [comment]
Hello, 
thanks for the reply. You were right, after a restart it finds the library.

I use this documentation: 
https://htmlpreview.github.io/?https://github.com/rahra/smrender/blob/master/doc/smrender.html

The version I used came via git (simply git clone https://github.com/rahra/smrender)

I had some trouble to compile it until I noticed, there was a note about /autoconf.sh (which is missing in the documentation). Also libcairo does not exist on debian, you have to use libcairo2. 

The biggest trouble I got right now is to generate some maps. There is a directory called "test" with some (like it seems) generated osm files fomr other sources. 
The Documentation gives very few informations about that - basically just one line: "We just use the Overpass API [25] to get a small window". The informations in the link look to me more like a coding guide. On openseamaps is a link to download JOSM (I guess the J stands for Java). However, since I could not find any guide or how-to, I don't even know if this is the correct tool to generate osm files for smrender...


PS:
- a broken link is e.g. link 2 (http://opencpn.org/ocpn/kap_format) goes to a 404 ;) 
- in section: 6.1.2  Drawing and Filling is a broken Link to a figure: https://htmlpreview.github.io/inc/depth_cont

**Comment by rahra** [comment]
Ok, that's a lot of questions ;)
The test directory is thought to be functional test for development which is still by far not complete. But it could serve as a sample for rendering primitives.

The input file format of Smrender is OSM which is the standard file format of the OSM project. There are almost endless possibilities of how to gather such data. The documentation just gives a view hints of how to get OSM files, since the topic of gathering OSM data could alone fill a master thesis ;)

JOSM is a Java-bases tool which you could use to download OSM data. It is easy to use and you can download it here: https://josm.openstreetmap.de/wiki/De%3ADownload

But as you already figured out yourself, OSM is very storage intensive because of the immense details. Although Smrender is very robust and you could feed files of tens of GBytes into it, I would recommend to use a different data source for creating pilot charts (Übersegler), such as Naturalearth: https://www.naturalearthdata.com/
Have a look at this page https://sailingaroundtheworld.wordpress.com/ubersegler/ for rendered charts produced by Smrender.
I'm willing to support you in creating your favorite pilot chart(s). Which region are you intersted in?

**Comment by kuttkutt** [comment]
Hey, yea I found the charts on sailingaround the world already.

Well I'm looking for some bigger ones. My girlfriend has her birthday end of this month and she loves to track our routes on paper charts. So not for navigating, just to look at it later. 

We want to take next year off and sail around the atlantic ocean and I am looking for some big charts  (A1 or A0) with at least 300 or 600dpi. (I gues you are from austria, so german may be not an issue - my blog is: https://martin-kuettner.de) 

My ship runs only on Arduinos and Rasperrys and I think that Linux, Coding and so on are not a problem for me, but I never got very close in touch with the OSM format - so newbee ;) 

Since you offered your help I would need some charts (DIN A1 or A0, 300 or better 600dpi) of the following boxes (Minutes are decimal, base 100):
58°00N, 19°15'E to 02°00'N, 69°00'W
58°00N, 19°15'E to 02°00'N, 40°00'W
45°00'N, 45°00'W to 02°00'N, 69°00'W
66°50'N, 29°30'E to 52°50'N, 09°00'E

(it's not exactly DIN format, but I'll print them in aspect and trim the paper)

I know, the files will be big, but I can give you an 100mBit FTP account on my server for uploading.

**Comment by rahra** [comment]
Ok, I'll have a look at it. Since Smrender is developed to produce paper charts in particular, I will refit your coordinates to fit to A0/A1. If you scale it with the printer the chart scale and chart projection will be destroyed. 
Smrender is vector based, thus there is not pixel resolution, the output will we a high resolution PDF but can easily be down-sampled to 300/600 dpi pixel image (e.g. PNG).
Here is a well-known example in A0, "Deutsche Bucht": https://www.cypherpunk.at/download/smrender/samples/INT-1463.pdf

**Comment by kuttkutt** [comment]
Hello, 

yea, I'm looking for something like this, but within the coordinates of my previous post. (the land does not have to be so detailed tho) 

Could you render those for me? I would need them till sunday to get them printed to have them ready as present ;) 

PS: if it's a vector graphics, that would be even better.
